### ISSUE TITLE
layout and behavior broken in flexbox environments

### ISSUE THREAD

**Issue by timove** [PolymerElements/iron-collapse#52] opened 2016-04-26 07:58 UTC
### Description
In certain flexbox environments `iron-collapse` fails to visually collapse itself and to report `transitionend` events. The `flex` character suppresses the `height` changes visually.

### Expected outcome
Visually collapsing `iron-collapse` and fired `transitionend` events.

### Actual outcome
No animation visible, content remains visible, no `transitionend` events. 

### Steps to reproduce
See failing test in https://github.com/timove/iron-collapse/commit/eec525b329c63d436c58cd7594917be296b09e2d

### Browsers Affected
Verified for, otherwise untested:
- [x] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [x] IE 11
- [ ] IE 10

**Comment by valdrinkoshi** [comment] 2016-05-23 20:40
Could not reproduce, the events are correctly fired: here http://jsbin.com/mecaha/1/edit?html,console,output
In those tests you have the `iron-collapse` already opened, hence you should not see any animation. If the status is toggled after the collapse gets attached, you should see the animation.
Closing for now, will reopen if the problem persists. A jsbin showing the issue would be much appreciated 👍

**Comment by timove** [comment] 2016-05-24 06:52
In your jsbin, the iron-flex-layout classes "layout, vertical" do not get applied to the container surrounding the iron-collapse. Here is a fixed version: http://jsbin.com/xudawucomo/1/edit?html,console,output 
I added a red background to illustrate the issue. transitionend does not fire when every 2nd time toggle is clicked. Can you confirm this?

**Comment by valdrinkoshi** [comment] 2016-05-24 07:19
@timove yes i confirm that transitionend doesn't get fired when iron-collapse is opened.
For your use case, I would rather suggest to wrap the iron-collapse with another div and make it flex, like this http://jsbin.com/gipaceruci/edit?html,output
WDYT?

**Comment by timove** [comment] 2016-05-25 15:18
@valdrinkoshi Unfortunately, in my use case this does not work. I cannot tell why, yet. I have nested iron-collapse elements which show really awkward behaviors without my proposed fixed. --- Do you see problems applying the fix?

**Comment by valdrinkoshi** [comment] 2016-05-25 16:27
Oh, I forgot reopening the issue sorry!
Will review your PR & see if this is a breaking change or not 😉

**Closed** 2016-06-07 18:58 UTC
Labels: bug, p1 - backlog, started

**Comment by valdrinkoshi** [comment] 2016-06-07 19:01
Released in `v1.1.0`
