### ISSUE TITLE
Make a smart iron-collapse that removes its content from the DOM when closed

### ISSUE THREAD

**Issue by mgiuffrida** [PolymerElements/iron-collapse#54] opened 2016-05-04 18:14 UTC
Kind of like putting <content> in a dom-if, but of course we can't do that.

Is this feasible with a templatizer?

**Comment by valdrinkoshi** [comment] 2016-05-04 18:24
That would cause many `attached/detached`, so it's better to just toggle the css `display` to `"none"` when closed (already done by `iron-collapse` [here](https://github.com/PolymerElements/iron-collapse/blob/master/iron-collapse.html#L63))

**Comment by mgiuffrida** [comment] 2016-05-04 20:01
doesn't `dom-if restamp` have the same behavior?

**Comment by valdrinkoshi** [comment] 2016-05-04 21:02
`restamp` will destroy & recreate its content. I don't see why the `iron-collapse` should do that, its job is to only hide and show the content, it doesn't have any say on its creation/destruction.

Anyways, you could just have a `template is="dom-if"` as content of the `iron-collapse`:
```html
<iron-collapse on-opened-changed="toggleShowContent">
  <template is="dom-if" if="{{showContent}}">
     your content
  </template>
</iron-collapse>

**Comment by mmpowers** [comment] 2016-05-23 20:15
@valdrinkoshi can you confirm that snippet works?  

When I try 

`    <iron-collapse id="collapse">
      <div>Content goes outside...{{isTrue()}}</div>
      <template id="dom-if" if="{{isTrue()}}">
        <div>Content goes inside...</div>
      </template>
    </iron-collapse>
`

It gets rendered as: 

`<iron-collapse id="collapse" class="style-scope word-item iron-collapse-opened" role="group" aria-hidden="false" aria-expanded="true" style="transition-property: height; height: auto; transition-duration: 0s;">
      <div class="style-scope word-item">Content goes outside...true</div>
      <template id="dom-if" class="style-scope word-item"></template>
  </iron-collapse>
`

**Comment by valdrinkoshi** [comment] 2016-05-23 20:26
@mmpowers I don't know what that `isTrue()` does, but looks like it gets executed once and its value is used for the binding. You should bind to a property & update it
Here an example http://jsbin.com/ponomuq/1/edit?html,output

**Comment by mmpowers** [comment] 2016-05-23 20:39
Apologies, had "<template id='dom-if'" instead of "<template is='dom-if'".  I guess I need a lint for that.

Confirmed: using dom-if works great for this purpose.

**Comment by valdrinkoshi** [comment] 2016-05-23 20:40
Awesome! 👍 
Closing this.

**Closed by valdrinkoshi** 2016-05-23 20:40 UTC
