### ISSUE TITLE
Setting opened vs. invoking show()

### ISSUE THREAD

**Issue by dulimarta** [PolymerElements/iron-collapse#22] opened 2015-08-28 19:27 UTC
I have the following snippet:

    <iron-collapse id="input_box">
      <div>
        <paper-material elevation="2">
          Text here
          <paper-input label="Your input"></paper-input>
        </paper-material>
      </div>
    </iron-collapse>

Invoking

    this.$$('#input_box').show()

briefly animated the `input_box` to open but **it closed immediately after**.

But, setting the `opened` attribute worked perfectly (including the slide down animation)

    this.$$('#input_box').opened = true

**Comment by valdrinkoshi** [comment] 2015-11-13 00:16
Hi @dulimarta, I cannot reproduce the bug, could you please verify again http://jsbin.com/bebafejaca/edit?html,output
closing for now

**Closed by valdrinkoshi** 2015-11-13 00:16 UTC
Labels: bug
